version: '3'

services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules

        entrypoint: npm
        command: start
        links:
            - redis
        ports:
            - "8000:8000"
        environment:
            - REDIS_HOST=redis
